# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: ["master"]
    
jobs:
 Build_and_Publish:
  runs-on: windows-latest
  steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 5.x.x
    - name: Restore dependencies
      run: dotnet restore 'PackageBuilder/TestPackage.wixproj'
    - name: Build
      run: dotnet build 'PackageBuilder/TestPackage.wixproj' -c Release
    - name: Zip files
      uses: vimtor/action-zip@v1
      with:
        files: PackageBuilder/bin/release/en-US
        dest: TestPackage.zip
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      with:
        tag_name: 1.0.${{ github.run_number }}
        release_name: 1.0.${{ github.run_number }}
        draft: false
        prerelease: false
    - name: Upload setup
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      with:
       upload_url: ${{ steps.create_release.outputs.upload_url }}
       asset_path: 'TestPackage.zip'
       asset_name: 'Testing_Console_v1.0.${{ github.run_number }}.zip'
       asset_content_type: application/zip
        
     
